admin/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

pasar/urls.py
from django.contrib import admin
from django.urls import path
from sishasembapo import views as pasar
from django.conf.urls.i18n import i18n_patterns

urlpatterns = i18n_patterns(
    path('admin/', admin.site.urls),
    path('',pasar.maps, name="maps"),
    path('login/', pasar.Login, name="login"),
    path('tabel/', pasar.index, name="index"),
    path('logout/', pasar.Logout, name="logout"),
    # CHANGE PASSWORD
    path('changepassword/<int:pk>', pasar.changepassword , name='changepassword'),
    path('profile/<int:pk>', pasar.profile, name='profile'),
    path('harga/', pasar.view_harga , name='list_harga_sembako'),
    path('harga/<int:pk>', pasar.update_harga , name='update_harga'),
    path('grafik/', pasar.view_grafik , name='grafik'),
    path('listharga',pasar.HargaList.as_view(), name='listharga'),
    prefix_default_language=False
)

sishasembapo/models.py
from django.db import models
from django.contrib.auth.models import User
from django.contrib.humanize.templatetags.humanize import intcomma
from django.template.defaultfilters import date
from location_field.models.plain import PlainLocationField
from mapbox_location_field.models import LocationField

# Create your models here.
class Pasar(models.Model):
    nama_pasar = models.CharField(max_length=100)
    alamat_pasar = models.TextField()
    kelurahan = models.CharField(max_length=100,null=True)
    kecamatan = models.CharField(max_length=100,null=True)
    notlp = models.CharField(max_length=13,null=True)
    lokasi = LocationField(map_attrs={"center": [111.999458,-7.817179], "marker_color": "blue", "placeholder": "Silahkan Pilih lokasi"})
    class Meta:
        db_table = "Tb_Pasar"
        verbose_name_plural = "Pasar"
    
    def __str__(self):
        return self.nama_pasar

class Sembako(models.Model):
    S_CHOICES = [
        ('Kg', 'Kg'),
        ('Perbiji', 'Perbiji'),
        ('Liter', 'Liter')
    ]
    nama_sembako = models.ForeignKey('self',null = True,blank=True,on_delete=models.CASCADE)
    jenis_sembako = models.CharField(max_length=50)
    satuan = models.CharField(max_length=20, choices=S_CHOICES, default='Kg')

    class Meta:
        db_table = "Tb_Sembako"
        verbose_name_plural = "Sembako"

    def __str__(self):
        if not self.nama_sembako:
            return "%s"%(self.jenis_sembako)
        else:
            return "%s - %s"%(self.nama_sembako,self.jenis_sembako)

class Harga(models.Model):
    class St(models.TextChoices):
            setuju = '1', 'Disetujui'
            tolak = '2', 'Ditolak'
            belum = '3', 'Belum Diperiksa'
        
    tanggal = models.DateField()
    nama_sembako = models.ForeignKey(Sembako,on_delete=models.CASCADE)
    nama_pasar = models.ForeignKey(Pasar,on_delete=models.CASCADE)
    nominal = models.IntegerField()
    validasi = models.CharField(max_length=2, choices=St.choices, default=St.belum)

    class Meta:
        db_table = "Tb_Harga"
        verbose_name_plural = "Harga"

    @property
    def harga(self):
        natural = intcomma(self.nominal)
        return "Rp. %s" % natural

    def __str__(self):
        return "%s - %s"%(self.nama_sembako.nama_sembako,self.nama_sembako.jenis_sembako)

class PetugasPasar(models.Model):
    JK_CHOICES = [
        ('LK', 'Laki - Laki'),
        ('PR', 'Wanita')
    ]
    akun = models.OneToOneField(
        User,
        on_delete=models.CASCADE,primary_key=True,
    )
    nama = models.CharField(max_length=100)
    jenis_kelamin = models.CharField(max_length=20, choices=JK_CHOICES, default='LK')
    tempat_lahir = models.CharField(max_length=100)
    Tanggal_lahir = models.DateField()
    alamat = models.TextField()
    pasar = models.ForeignKey(Pasar,on_delete=models.CASCADE)
    No_hp = models.CharField(max_length=100)

    def __str__(self):
        return self.nama

    class Meta:
        db_table = "tb_Petugas_Pasar"
        verbose_name_plural = "Petugas Pasar"

    

sishasembapo/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth import authenticate, logout, login, update_session_auth_hash
from sishasembapo.models import *
from sishasembapo.form import *
from django.db import connection
from django.http import HttpResponse,FileResponse, Http404, HttpResponseRedirect
from django.contrib.auth.hashers import make_password,check_password
from django.contrib.auth.decorators import login_required
import datetime
from django.db import connection
from django.db.models import Q, Avg
from django.utils import translation
from django.db.models.functions import Coalesce
from .serializers import *
from django.core import serializers
from django.core.serializers import serialize 
from rest_framework import generics

def Login(request):
    if request.POST:
        user = authenticate(username=request.POST['login_username'], password=request.POST['login_password'])
        if user is not None:
            if not user.is_staff:
                try:
                    profil = PetugasPasar.objects.get(akun_id=user.id)
                    login(request, user)
                    request.session['nama'] = profil.nama
                    request.session['pasar'] = profil.pasar.nama_pasar
                    request.session['idpasar'] = profil.pasar.id
                    request.session['id'] = user.id
                    if 'next' in request.POST:
                        return redirect(request.POST.get('next'))
                    elif 'url' in request.session:
                        return redirect(request.session['url'])
                    else:
                        return redirect('/')
                except PetugasPasar.DoesNotExist:
                    messages.add_message(request, messages.INFO, 'Akun Tersebut Belum Terintegrasi Dengan Petugas Pasar Manapun, Silahkan Hubungi Admin PD. Pasar')
                    return redirect(request.META['HTTP_REFERER'])
            else:
                messages.add_message(request, messages.INFO, 'Akun Tersebut Bukan Termasuk Akun Petugas Pasar')
                return redirect(request.META['HTTP_REFERER'])
        else:
            messages.add_message(request, messages.INFO, 'Username atau password Anda salah')
            return redirect(request.META['HTTP_REFERER'])
    return render(request, 'login.html')

def index(request):
    request.session['url'] = request.get_full_path()
    ambilpasar = Pasar.objects.all()
    ambilsembakosemua = Sembako.objects.annotate(induk=Coalesce('nama_sembako','id')).order_by('induk','id')
    pencarian = []
    date_isi = []
    if request.method == "POST":
        ambiltanggal = request.POST['tanggal']
        ambilpasar1 = request.POST.get('nama_pasar')
        tanggal = datetime.datetime.strptime(ambiltanggal,'%Y-%m-%d')
        kemarin = datetime.timedelta(days=1)
        date_isi.append({ "kemarin":tanggal - kemarin, "tanggal":tanggal,'pasar':ambilpasar1})
        pencarian.append({ "pasar":Pasar.objects.get(id=ambilpasar1).nama_pasar,"tanggal":tanggal})
    else:
        ambiltanggal = datetime.datetime.now().date()
        ambiltanggal1 = datetime.datetime.strftime(ambiltanggal,'%Y-%m-%d')
        if 'pasar' not in request.session:
            ambilpasar1 = 1
        else:
            ambilpasar1 = ambilpasar.get(nama_pasar=request.session['pasar']).id
        kemarin = datetime.timedelta(days=1)
        date_isi.append({ "kemarin":ambiltanggal - kemarin, "tanggal":ambiltanggal,'pasar':ambilpasar1})
        pencarian.append({ "pasar":Pasar.objects.get(id=ambilpasar1).nama_pasar,"tanggal":ambiltanggal})
   
    data = []
    for sem in ambilsembakosemua:
        sekarang = 0
        kemarin = 0
        perubahan = 0
        persen = 0
        if sem.nama_sembako:
            for dd in date_isi:
                ambilsembakos = Harga.objects.filter(tanggal=dd['tanggal'],nama_sembako__id=sem.id,validasi=Harga.St.setuju,nama_pasar__id=dd['pasar']).order_by('-id').first()
                if ambilsembakos:
                    sekarang = ambilsembakos.nominal
                else:
                    sekarang = 0

                ambilkemarin = Harga.objects.filter(tanggal=dd['kemarin'],nama_sembako__id=sem.id,validasi=Harga.St.setuju,nama_pasar__id=dd['pasar']).order_by('-id').first()
                if ambilkemarin:
                    kemarin = ambilkemarin.nominal
                else:
                    kemarin = 0

                perubahan = sekarang - kemarin
                if sekarang and kemarin:
                    persen = round(((sekarang-kemarin)/kemarin)*100,2)
                else:
                    persen = 0
        data.append({"induk":sem.nama_sembako,'jenis':sem.jenis_sembako,"sekarang":sekarang,"kemarin":kemarin,"satuan":sem.satuan,"perubahan":perubahan,"persen":persen})
    return render(request, 'pengunjung/index.html',{'pasar':ambilpasar,'sembakosemua':data,"pencarian":pencarian})

def Logout(request):
    logout(request)
    for key in request.session.keys():
        del request.session[key]
    return redirect('/') 

# CHANGEPASSWORD 
@login_required(login_url='/login')
def changepassword(request,pk):
    pesan = []
    user = User.objects.filter(id = request.session['id']).first()
    if request.method == "POST":
        old_password = request.POST['old_password']
        comnewpassword = request.POST['confrim_password']
        newpassword = request.POST['password']
        form = User_form(request.POST, instance=user)
        if check_password(old_password, user.password):
            if newpassword == comnewpassword:
                if form.is_valid():
                    newpw = form.save(commit=False)
                    newpw.username = user.username
                    newpw.password = make_password(newpassword)
                    newpw.save()
                    pesan.append({"id":"1","status":"success","messages":"Sandi berhasil dirubah"})
                    update_session_auth_hash(request, form.instance)
            else:
                pesan.append({"id":"2","status":"danger","messages":"Sandi baru tidak cocok. Masukkan sekali lagi."})
        else:
            pesan.append({"id":"3","status":"danger","messages":"Sandi lama yang anda masuk salah. Masukkan sekali lagi."})
    else:
        form = User_form(instance=user)
    return render(request, 'changepassword.html', {'form': form, 'user' : user,'pesan':pesan})

@login_required(login_url='/login')
def profile(request,pk):
    request.session['url'] = request.get_full_path()
    user = PetugasPasar.objects.filter(akun_id = request.session['id']).first()
    translation.activate('id')
    return render(request, 'changeprofile.html', {'user' : user})

@login_required(login_url='/login')
def view_harga(request):
    ambil_pasar = Pasar.objects.get(nama_pasar=request.session['pasar'])
    list_harga = Harga.objects.filter(nama_pasar = ambil_pasar.id,tanggal=datetime.datetime.now()).order_by('-id')
    kemarin = datetime.date.today() - datetime.timedelta(days=1)
    harga_kemarin = Harga.objects.filter(nama_pasar = ambil_pasar.id,tanggal=kemarin,validasi=Harga.St.setuju)
    return render(request,'admin_pasar/Harga.html', {'harga':list_harga,'kemarin':harga_kemarin})

@login_required(login_url='/login')
def update_harga(request,pk):
    ambil_pasar = Pasar.objects.get(nama_pasar=request.session['pasar'])
    harga = Harga.objects.get(pk=pk)
    sembako = Sembako.objects.get(pk=harga.nama_sembako.id)
    if request.method == "POST":
        cursor = connection.cursor()
        cursor.execute("update tb_harga set nominal='%s' , validasi=3 where id='%s'"%(request.POST['nominal'],pk))
    else:
        form = Harga_form(instance=harga)
    return render(request,'admin_pasar/edit_harga.html',{'form':form,'harga':harga})

def view_grafik(request):
    request.session['url'] = request.get_full_path()
    ambil_pasar = Pasar.objects.all()
    ambil_Sembako = Sembako.objects.filter(nama_sembako__isnull=False).order_by('nama_sembako')
    x = datetime.datetime.now()
    data_isi1 = []
    pencarian1 = []
    if request.method == "POST":
        nama_pasar = request.POST['nama_pasar']
        nama_bahan = request.POST.get('nama_bahan')
        tahun1 = request.POST['tahun']
        tahun = datetime.date(year=int(tahun1),month=1,day=1).year
        if nama_pasar == "semua":
            data_isi1.append({"pasar":"semua","nama_bahan":Sembako.objects.get(id=nama_bahan).id,"tahun":tahun})
            pencarian1.append({"pasar":"Semua Pasar","tahun":tahun,"nama_bahan":Sembako.objects.get(id=nama_bahan).nama_sembako.jenis_sembako,"nama_jenis":Sembako.objects.get(id=nama_bahan).jenis_sembako,"satuan":Sembako.objects.get(id=nama_bahan).satuan})
        else:
            data_isi1.append({"nama_pasar":Pasar.objects.get(id=nama_pasar).id,"nama_bahan":Sembako.objects.get(id=nama_bahan).id,"tahun":tahun})
            pencarian1.append({"Semua Pasar":Pasar.objects.get(id=nama_pasar).nama_pasar,"tahun":tahun,"nama_bahan":Sembako.objects.get(id=nama_bahan).nama_sembako.jenis_sembako,"nama_jenis":Sembako.objects.get(id=nama_bahan).jenis_sembako,"satuan":Sembako.objects.get(id=nama_bahan).satuan})
    else:
        if 'pasar' not in request.session:
            nama_pasar = str(ambil_pasar.first().id)
        else:
            nama_pasar = str(ambil_pasar.get(nama_pasar=request.session['pasar']).id)
        nama_bahan = "28"
        tahun = x.year
        data_isi1.append({"nama_pasar":nama_pasar,"nama_bahan":nama_bahan,"tahun":tahun})
        pencarian1.append({"pasar":Pasar.objects.get(id=nama_pasar).nama_pasar,"tahun":tahun,"nama_bahan":Sembako.objects.get(id=nama_bahan).nama_sembako.jenis_sembako,"nama_jenis":Sembako.objects.get(id=nama_bahan).jenis_sembako,"satuan":Sembako.objects.get(id=nama_bahan).satuan})
    # Grafik Besar
    listpasar = []
    setono=[]
    pahing=[]
    banjaran=[]
    bawang=[]
    ngronggo=[]
    ngalim=[]
    bandar=[]
    mrican =[]
    for i in data_isi1:

sishasembapo/templates/admin_pasar/edit_harga.html
    {% extends "layout/pengunjung/base_pengunjung.html" %}
    
    {% load static %}
    {% load humanize %}
    
    {% block extrastyle %}
    <link rel="stylesheet" href="{% static 'assets_page/plugins/toastr/toastr.min.css'%}">
    <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/select2/3.5.2/select2.css">
    <style type="text/css">
      #navbar-hide{ display:none; }
      label[for="id_validasi"]
      {
          display:none;
      }
        label{
            font-size: small;
        }
        html, body {margin: 0; height: 100%; overflow: hidden}
        form{
          font-size: medium;
        }
    </style>
    {% endblock extrastyle %}
    
    {% block content %}
    <section class="content-header">
        <div class="card">
            <div class="card-header" style="text-align: center;">
                <h4><b>Ubah Harga {{harga.nama_sembako}}</b></h4>
                <h5>tanggal: {{harga.tanggal}}</h5>
            </div>
            <div class="card-body">
                <form method="POST" action="{% url 'update_harga' pk=harga.pk %}">
                    {% csrf_token %}
                    {{form.as_p}}
                    <div style="text-align: center;">
                        <button type="submit" class="btn btn-s" style="background-color:#417690; color: white;">Simpan</button>
                        <button type="button" class="btn btn-s" style="background-color:#79aec8; color: white;" onclick="return window.close();">Batal</button>
                    </div>
                </form>
            </div>
        </div>
    </section>
    {% endblock content %}
    
    {% block extrajs %}
    <script type="text/javascript" src="http://cdn.jsdelivr.net/select2/3.4.6/select2.min.js"></script>
    <script>
        $("#id_nama_sembako").attr("disabled",true);
        function btn_simpan() {
          window.onunload = refreshParent;
          function refreshParent() {
            window.opener.location.replace("{% url 'list_harga_sembako' %}");
          }
          window.close()
        }

        const swalWithBootstrapButtons = Swal.mixin({
            buttonsStyling: true
          })

        $(document).ready(function() {
            $("form").submit(function() {
                swal.fire({
                    title: 'Apakah Anda Yakin?',
                    text: "",
                    icon: 'question',
                    showCancelButton: true,
                    confirmButtonText: 'Ya',
                    confirmButtonColor:'#417690',
                    cancelButtonText: 'Tidak',
                    cancelButtonColor: '#79aec8',
                    reverseButtons: false
                  }).then((result) => {
                    if (result.value) {
                    $.post($("form").attr('action'), $("form").serializeArray());
                      swal.fire({
                        icon: 'success',
                        title: 'Data Berhasil diubah',
                        showConfirmButton: false,
                        timer: 1500
                      }).then(function() {
                        btn_simpan();
                      })
                    } else if (
                      result.dismiss === Swal.DismissReason.cancel
                    ) {
                      swal.fire(
                        'Batal',
                        '',
                        'error'
                      )
                    }
                  })
              return false;
            });
          });
    </script>
    {% endblock extrajs %}

sishasembapo/templates/admin_pasar/maps.html
{% extends "layout/pengunjung/base_pengunjung.html" %}
{% load static %}
{% load humanize %}

{% block extrastyle %}
<link href='https://api.mapbox.com/mapbox-gl-js/v1.8.0/mapbox-gl.css' rel='stylesheet' />
<link rel="stylesheet" href="https://api.mapbox.com/mapbox-gl-js/plugins/mapbox-gl-geocoder/v4.4.2/mapbox-gl-geocoder.css" type="text/css" />
{% endblock extrastyle %}

{% block content %}
<section class="content-header">
    <div style="text-align: center;">
        <h3 class="judul">SELAMAT DATANG DI SISTEM INFORMASI SEMBILAN HARGA BAHAN POKOK</h3>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/es6-promise@4/dist/es6-promise.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/es6-promise@4/dist/es6-promise.auto.min.js"></script>
    <div id='map' style='width: 100%; height: 600px;'></div>
    <form id="myform" method="post" action="{% url 'index' %}">
        {% csrf_token %}
        <input type="hidden" name="tanggal" value="{% now 'Y-m-d' %}"/>
        <input type="hidden" id="nama_pasar" name="nama_pasar"/>
        <a href="#" name="submit"></a>
    </form>
</section>
{% endblock content %}

{% block extrajs %}
<script src='https://api.mapbox.com/mapbox-gl-js/v1.8.0/mapbox-gl.js'></script>
<script src="https://api.mapbox.com/mapbox-gl-js/plugins/mapbox-gl-geocoder/v4.4.2/mapbox-gl-geocoder.min.js"></script>
<script>
    var options = {
        enableHighAccuracy: true
    };
    
    function success(pos) {
        crd = pos.coords;
        loadMap(crd.longitude,crd.latitude);
    };
    
    function error(err) {
        console.log('ERROR');
        loadMap(111.999458, -7.817179);
    };
    
    navigator.geolocation.getCurrentPosition(success, error, options);
    var geojson = {
        'type': 'FeatureCollection',
        'features': [
        {% for list in pasar %}
        {
            'type': 'Feature',
            'properties': {
                'id_pasar':'{{list.id}}',
                'nama_pasar':'{{list.nama_pasar}}',
                'description':
                '<br>{{list.alamat}}, Kel.{{list.kel}}, Kec.{{list.kec}}. <br>{{list.tlp}} <br><strong>Harga Bahan Pokok Hari Ini</strong><marquee scrollamount="4">{% if not list.harga %}Tidak ada data harga sembako hari ini{% else %}{% for a in list.harga %}({{a.nama_sembako}} <=> {{a.harga|intcomma}},00.), {% endfor %}{% endif %}</marquee><br>',
                'icon': 'grocery'
                
            },
            'geometry': {
                'type': 'Point',
                'coordinates': [{{list.lng}},{{list.lat}}]//(longitude,lalitude)
            }
        },
        {% endfor %}
        ]
    };
    function loadMap(lng,lat) {
        mapboxgl.accessToken = '{{api}}';
        var map = new mapboxgl.Map({
            container: 'map', // container id
            style: 'mapbox://styles/mapbox/streets-v11', // stylesheet location
            center: [lng,lat], // starting position [lng, lat]
            zoom: 13 // starting zoom
        });
        map.on('load', function() {
            map.addSource(
            'places', {
                'type': 'geojson',
                'data': geojson
            }
            ),
            
            // Add a layer showing the places.
            map.addLayer({
                'id': 'places',
                'type': 'symbol',
                'source': 'places',
                'layout': {
                    'text-field': ['get', 'nama_pasar'],
                    'text-size': 10,
                    'text-offset': [0, 0.6],
                    'text-anchor': 'top',
                    'icon-image': '{icon}-15',
                    'icon-allow-overlap': true
                }
            });
            
            // Create a popup, but don't add it to the map yet.
            var popup = new mapboxgl.Popup({
                closeButton: false,
                closeOnClick: true,
                minWidth: 80,
                maxWidth: window.innerWidth - 300,
            }).setMaxWidth("350px");
            
            //console.log(screen.width);
            map.on('mouseenter', 'places', function(e) {
                map.getCanvas().style.cursor = 'pointer';
                map.scrollZoom.enable();
            });

            map.on('click', 'places', function(e) {
                map.flyTo({ center: e.features[0].geometry.coordinates ,zoom: 15 });
                // Change the cursor style as a UI indicator.
                var coordinates = e.features[0].geometry.coordinates.slice();
                var description = e.features[0].properties.description;
                var id = e.features[0].properties.id_pasar;
                
                // Ensure that if the map is zoomed out such that multiple
                // copies of the feature are visible, the popup appears
                // over the copy being pointed to.
                while (Math.abs(e.lngLat.lng - coordinates[0]) > 180) {
                    coordinates[0] += e.lngLat.lng > coordinates[0] ? 360 : -360;
                }
                
                // Populate the popup and set its coordinates
                // based on the feature found.
                popup
                .setLngLat(coordinates)
                .setHTML(Objects(e))
                .addTo(map);

                document.getElementById('btn-submit').addEventListener('click', function() {
                    document.getElementById("nama_pasar").setAttribute("value",id)
                    document.getElementsByName("submit").onclick = document.forms[0].submit();
                });
            });
            
            map.on('mouseleave', 'places', function() {
                map.getCanvas().style.cursor = '';
                map.scrollZoom.disable();
            });     
        });
        function Objects(e) {
            var html = '';
            html += "<strong><center><font size='3'>" + e.features[0].properties.nama_pasar + "</font></center></strong>" + e.features[0].properties.description;
            html += "<button class='btn btn-secondary btn-block' style='background-color:#417690; color: white;' id='btn-submit' value='Detail'>Detail</button>";
            return html;
        }
        map.addControl(new MapboxGeocoder({
            accessToken: mapboxgl.accessToken,
            mapboxgl: mapboxgl
        })
        );
        map.addControl(new mapboxgl.FullscreenControl());
        map.addControl(new mapboxgl.NavigationControl());
        map.addControl(new mapboxgl.GeolocateControl({
            positionOptions: {
                enableHighAccuracy: true
            },
            trackUserLocation: true,
        })
        );
    }
    // Add geolocate control to the map.
</script>
{% endblock extrajs %}