admin/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

pasar/urls.py
from django.contrib import admin
from django.urls import path
from sishasembapo import views as pasar
from django.conf.urls.i18n import i18n_patterns

urlpatterns = i18n_patterns(
    path('admin/', admin.site.urls),
    path('',pasar.maps, name="maps"),
    path('login/', pasar.Login, name="login"),
    path('tabel/', pasar.index, name="index"),
    path('logout/', pasar.Logout, name="logout"),
    # CHANGE PASSWORD
    path('changepassword/<int:pk>', pasar.changepassword , name='changepassword'),
    path('profile/<int:pk>', pasar.profile, name='profile'),
    path('harga/', pasar.view_harga , name='list_harga_sembako'),
    path('harga/<int:pk>', pasar.update_harga , name='update_harga'),
    path('grafik/', pasar.view_grafik , name='grafik'),
    path('listharga',pasar.HargaList.as_view(), name='listharga'),
    prefix_default_language=False
)

sishasembapo/models.py
from django.db import models
from django.contrib.auth.models import User
from django.contrib.humanize.templatetags.humanize import intcomma
from django.template.defaultfilters import date
from location_field.models.plain import PlainLocationField
from mapbox_location_field.models import LocationField

# Create your models here.
class Pasar(models.Model):
    nama_pasar = models.CharField(max_length=100)
    alamat_pasar = models.TextField()
    kelurahan = models.CharField(max_length=100,null=True)
    kecamatan = models.CharField(max_length=100,null=True)
    notlp = models.CharField(max_length=13,null=True)
    lokasi = LocationField(map_attrs={"center": [111.999458,-7.817179], "marker_color": "blue", "placeholder": "Silahkan Pilih lokasi"})
    class Meta:
        db_table = "Tb_Pasar"
        verbose_name_plural = "Pasar"
    
    def __str__(self):
        return self.nama_pasar

class Sembako(models.Model):
    S_CHOICES = [
        ('Kg', 'Kg'),
        ('Perbiji', 'Perbiji'),
        ('Liter', 'Liter')
    ]
    nama_sembako = models.ForeignKey('self',null = True,blank=True,on_delete=models.CASCADE)
    jenis_sembako = models.CharField(max_length=50)
    satuan = models.CharField(max_length=20, choices=S_CHOICES, default='Kg')

    class Meta:
        db_table = "Tb_Sembako"
        verbose_name_plural = "Sembako"

    def __str__(self):
        if not self.nama_sembako:
            return "%s"%(self.jenis_sembako)
        else:
            return "%s - %s"%(self.nama_sembako,self.jenis_sembako)

class Harga(models.Model):
    class St(models.TextChoices):
            setuju = '1', 'Disetujui'
            tolak = '2', 'Ditolak'
            belum = '3', 'Belum Diperiksa'
        
    tanggal = models.DateField()
    nama_sembako = models.ForeignKey(Sembako,on_delete=models.CASCADE)
    nama_pasar = models.ForeignKey(Pasar,on_delete=models.CASCADE)
    nominal = models.IntegerField()
    validasi = models.CharField(max_length=2, choices=St.choices, default=St.belum)

    class Meta:
        db_table = "Tb_Harga"
        verbose_name_plural = "Harga"

    @property
    def harga(self):
        natural = intcomma(self.nominal)
        return "Rp. %s" % natural

    def __str__(self):
        return "%s - %s"%(self.nama_sembako.nama_sembako,self.nama_sembako.jenis_sembako)

class PetugasPasar(models.Model):
    JK_CHOICES = [
        ('LK', 'Laki - Laki'),
        ('PR', 'Wanita')
    ]
    akun = models.OneToOneField(
        User,
        on_delete=models.CASCADE,primary_key=True,
    )
    nama = models.CharField(max_length=100)
    jenis_kelamin = models.CharField(max_length=20, choices=JK_CHOICES, default='LK')
    tempat_lahir = models.CharField(max_length=100)
    Tanggal_lahir = models.DateField()
    alamat = models.TextField()
    pasar = models.ForeignKey(Pasar,on_delete=models.CASCADE)
    No_hp = models.CharField(max_length=100)

    def __str__(self):
        return self.nama

    class Meta:
        db_table = "tb_Petugas_Pasar"
        verbose_name_plural = "Petugas Pasar"

    

sishasembapo/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth import authenticate, logout, login, update_session_auth_hash
from sishasembapo.models import *
from sishasembapo.form import *
from django.db import connection
from django.http import HttpResponse,FileResponse, Http404, HttpResponseRedirect
from django.contrib.auth.hashers import make_password,check_password
from django.contrib.auth.decorators import login_required
import datetime
from django.db import connection
from django.db.models import Q, Avg
from django.utils import translation
from django.db.models.functions import Coalesce
from .serializers import *
from django.core import serializers
from django.core.serializers import serialize 
from rest_framework import generics

def Login(request):
    if request.POST:
        user = authenticate(username=request.POST['login_username'], password=request.POST['login_password'])
        if user is not None:
            if not user.is_staff:
                try:
                    profil = PetugasPasar.objects.get(akun_id=user.id)
                    login(request, user)
                    request.session['nama'] = profil.nama
                    request.session['pasar'] = profil.pasar.nama_pasar
                    request.session['idpasar'] = profil.pasar.id
                    request.session['id'] = user.id
                    if 'next' in request.POST:
                        return redirect(request.POST.get('next'))
                    elif 'url' in request.session:
                        return redirect(request.session['url'])
                    else:
                        return redirect('/')
                except PetugasPasar.DoesNotExist:
                    messages.add_message(request, messages.INFO, 'Akun Tersebut Belum Terintegrasi Dengan Petugas Pasar Manapun, Silahkan Hubungi Admin PD. Pasar')
                    return redirect(request.META['HTTP_REFERER'])
            else:
                messages.add_message(request, messages.INFO, 'Akun Tersebut Bukan Termasuk Akun Petugas Pasar')
                return redirect(request.META['HTTP_REFERER'])
        else:
            messages.add_message(request, messages.INFO, 'Username atau password Anda salah')
            return redirect(request.META['HTTP_REFERER'])
    return render(request, 'login.html')

def index(request):
    request.session['url'] = request.get_full_path()
    ambilpasar = Pasar.objects.all()
    ambilsembakosemua = Sembako.objects.annotate(induk=Coalesce('nama_sembako','id')).order_by('induk','id')
    pencarian = []
    date_isi = []
    if request.method == "POST":
        ambiltanggal = request.POST['tanggal']
        ambilpasar1 = request.POST.get('nama_pasar')
        tanggal = datetime.datetime.strptime(ambiltanggal,'%Y-%m-%d')
        kemarin = datetime.timedelta(days=1)
        date_isi.append({ "kemarin":tanggal - kemarin, "tanggal":tanggal,'pasar':ambilpasar1})
        pencarian.append({ "pasar":Pasar.objects.get(id=ambilpasar1).nama_pasar,"tanggal":tanggal})
    else:
        ambiltanggal = datetime.datetime.now().date()
        ambiltanggal1 = datetime.datetime.strftime(ambiltanggal,'%Y-%m-%d')
        if 'pasar' not in request.session:
            ambilpasar1 = 1
        else:
            ambilpasar1 = ambilpasar.get(nama_pasar=request.session['pasar']).id
        kemarin = datetime.timedelta(days=1)
        date_isi.append({ "kemarin":ambiltanggal - kemarin, "tanggal":ambiltanggal,'pasar':ambilpasar1})
        pencarian.append({ "pasar":Pasar.objects.get(id=ambilpasar1).nama_pasar,"tanggal":ambiltanggal})
   
    data = []
    for sem in ambilsembakosemua:
        sekarang = 0
        kemarin = 0
        perubahan = 0
        persen = 0
        if sem.nama_sembako:
            for dd in date_isi:
                ambilsembakos = Harga.objects.filter(tanggal=dd['tanggal'],nama_sembako__id=sem.id,validasi=Harga.St.setuju,nama_pasar__id=dd['pasar']).order_by('-id').first()
                if ambilsembakos:
                    sekarang = ambilsembakos.nominal
                else:
                    sekarang = 0

                ambilkemarin = Harga.objects.filter(tanggal=dd['kemarin'],nama_sembako__id=sem.id,validasi=Harga.St.setuju,nama_pasar__id=dd['pasar']).order_by('-id').first()
                if ambilkemarin:
                    kemarin = ambilkemarin.nominal
                else:
                    kemarin = 0

                perubahan = sekarang - kemarin
                if sekarang and kemarin:
                    persen = round(((sekarang-kemarin)/kemarin)*100,2)
                else:
                    persen = 0
        data.append({"induk":sem.nama_sembako,'jenis':sem.jenis_sembako,"sekarang":sekarang,"kemarin":kemarin,"satuan":sem.satuan,"perubahan":perubahan,"persen":persen})
    return render(request, 'pengunjung/index.html',{'pasar':ambilpasar,'sembakosemua':data,"pencarian":pencarian})

def Logout(request):
    logout(request)
    for key in request.session.keys():
        del request.session[key]
    return redirect('/') 

# CHANGEPASSWORD 
@login_required(login_url='/login')
def changepassword(request,pk):
    pesan = []
    user = User.objects.filter(id = request.session['id']).first()
    if request.method == "POST":
        old_password = request.POST['old_password']
        comnewpassword = request.POST['confrim_password']
        newpassword = request.POST['password']
        form = User_form(request.POST, instance=user)
        if check_password(old_password, user.password):
            if newpassword == comnewpassword:
                if form.is_valid():
                    newpw = form.save(commit=False)
                    newpw.username = user.username
                    newpw.password = make_password(newpassword)
                    newpw.save()
                    pesan.append({"id":"1","status":"success","messages":"Sandi berhasil dirubah"})
                    update_session_auth_hash(request, form.instance)
            else:
                pesan.append({"id":"2","status":"danger","messages":"Sandi baru tidak cocok. Masukkan sekali lagi."})
        else:
            pesan.append({"id":"3","status":"danger","messages":"Sandi lama yang anda masuk salah. Masukkan sekali lagi."})
    else:
        form = User_form(instance=user)
    return render(request, 'changepassword.html', {'form': form, 'user' : user,'pesan':pesan})

@login_required(login_url='/login')
def profile(request,pk):
    request.session['url'] = request.get_full_path()
    user = PetugasPasar.objects.filter(akun_id = request.session['id']).first()
    translation.activate('id')
    return render(request, 'changeprofile.html', {'user' : user})

@login_required(login_url='/login')
def view_harga(request):
    ambil_pasar = Pasar.objects.get(nama_pasar=request.session['pasar'])
    list_harga = Harga.objects.filter(nama_pasar = ambil_pasar.id,tanggal=datetime.datetime.now()).order_by('-id')
    kemarin = datetime.date.today() - datetime.timedelta(days=1)
    harga_kemarin = Harga.objects.filter(nama_pasar = ambil_pasar.id,tanggal=kemarin,validasi=Harga.St.setuju)
    return render(request,'admin_pasar/Harga.html', {'harga':list_harga,'kemarin':harga_kemarin})

@login_required(login_url='/login')
def update_harga(request,pk):
    ambil_pasar = Pasar.objects.get(nama_pasar=request.session['pasar'])
    harga = Harga.objects.get(pk=pk)
    sembako = Sembako.objects.get(pk=harga.nama_sembako.id)
    if request.method == "POST":
        cursor = connection.cursor()
        cursor.execute("update tb_harga set nominal='%s' , validasi=3 where id='%s'"%(request.POST['nominal'],pk))
    else:
        form = Harga_form(instance=harga)
    return render(request,'admin_pasar/edit_harga.html',{'form':form,'harga':harga})

def view_grafik(request):
    request.session['url'] = request.get_full_path()
    ambil_pasar = Pasar.objects.all()
    ambil_Sembako = Sembako.objects.filter(nama_sembako__isnull=False).order_by('nama_sembako')
    x = datetime.datetime.now()
    data_isi1 = []
    pencarian1 = []
    if request.method == "POST":
        nama_pasar = request.POST['nama_pasar']
        nama_bahan = request.POST.get('nama_bahan')
        tahun1 = request.POST['tahun']
        tahun = datetime.date(year=int(tahun1),month=1,day=1).year
        if nama_pasar == "semua":
            data_isi1.append({"pasar":"semua","nama_bahan":Sembako.objects.get(id=nama_bahan).id,"tahun":tahun})
            pencarian1.append({"pasar":"Semua Pasar","tahun":tahun,"nama_bahan":Sembako.objects.get(id=nama_bahan).nama_sembako.jenis_sembako,"nama_jenis":Sembako.objects.get(id=nama_bahan).jenis_sembako,"satuan":Sembako.objects.get(id=nama_bahan).satuan})
        else:
            data_isi1.append({"nama_pasar":Pasar.objects.get(id=nama_pasar).id,"nama_bahan":Sembako.objects.get(id=nama_bahan).id,"tahun":tahun})
            pencarian1.append({"Semua Pasar":Pasar.objects.get(id=nama_pasar).nama_pasar,"tahun":tahun,"nama_bahan":Sembako.objects.get(id=nama_bahan).nama_sembako.jenis_sembako,"nama_jenis":Sembako.objects.get(id=nama_bahan).jenis_sembako,"satuan":Sembako.objects.get(id=nama_bahan).satuan})
    else:
        if 'pasar' not in request.session:
            nama_pasar = str(ambil_pasar.first().id)
        else:
            nama_pasar = str(ambil_pasar.get(nama_pasar=request.session['pasar']).id)
        nama_bahan = "28"
        tahun = x.year
        data_isi1.append({"nama_pasar":nama_pasar,"nama_bahan":nama_bahan,"tahun":tahun})
        pencarian1.append({"pasar":Pasar.objects.get(id=nama_pasar).nama_pasar,"tahun":tahun,"nama_bahan":Sembako.objects.get(id=nama_bahan).nama_sembako.jenis_sembako,"nama_jenis":Sembako.objects.get(id=nama_bahan).jenis_sembako,"satuan":Sembako.objects.get(id=nama_bahan).satuan})
    # Grafik Besar
    listpasar = []
    setono=[]
    pahing=[]
    banjaran=[]
    bawang=[]
    ngronggo=[]
    ngalim=[]
    bandar=[]
    mrican =[]
    for i in data_isi1:

sishasembapo/templates/changepassword.html
{% extends  "layout/pengunjung/base_pengunjung.html" %}

{% load static %}

{% block extrastyle %}
<link rel="stylesheet" href="/static/assets/bootstrap/css/bootstrap-select.css">
<style>
    @media (max-width: 450px) {
        h3 {
            font-size: x-large;
        }
        label {
            font-size: medium;
        }
    }
</style>
{% endblock%}

{% block content %}

<section class="content-header">
    <center>
        <div class="card col-md-5" style="text-align: left;">
            <div class="card-body">
                <div class="box box-primary col-md-12">
                    <div class="box-header with-border">
                        <h3 class="box-title" style="text-align:center;"><i class="fa fa-edit"></i> Ubah Kata Sandi <b> - {{ request.session.nama.split | first }}</b></h3>
                    </div>
                    <!-- /.box-header -->
                    <!-- form start -->
                    <div class="col-md-12 col-xs-12 col-lg-12">
                        {% if pesan %}
                        <p class="card-text">
                            <div class="form-group">
                                <div class="col-sm-12">
                                        {% for i in pesan %}
                                        <div class="alert alert-{{i.status}}">
                                        <h5 style="text-align:center; color: white;">{{ i.messages }}</h5>
                                        <input type="hidden" id="status" value="{{i.id}}">
                                    </div>
                                        {% endfor %}
                                </div>
                            </div>
                        </p>
                        {% endif %}
                        <div id="isi">
                        <form class="form-horizontal" action="{% url 'changepassword' pk=user.pk %}" method="POST">
                            {% csrf_token %}
                            <p class="card-text">
                                <div class="form-group">
                                    <label for="username" class="col-sm-6 control-label">Nama Pengguna: </label>
                                    <div class="col-sm-12">
                                        {{form.username}}
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label for="old_password" class="col-sm-6 control-label">Sandi Lama: </label>
                                    <div class="col-sm-12">
                                        <input type="password" name="old_password" class="form-control" placeholder="Isikan Sandi Lama" required="" id="id_old_password">
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label for="first_name" class="col-sm-6 control-label">Sandi Baru: </label>
                                    <div class="col-sm-12">
                                        {{form.password}}
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label for="confrim_password" class="col-sm-6 control-label">Konfirmasi Sandi Baru: </label>
                                    <div class="col-sm-12">
                                        <input type="password" name="confrim_password" class="form-control" placeholder="Isikan Sandi Baru" required="" id="id_confrim_password">
                                    </div>
                                </div>
                            </p>
                            <div style="text-align: center;">
                                <button type="button" class="btn" style="background-color:#417690; color: white;" data-toggle="modal" data-target="#myModal">Ubah</button>
                                <input type="button" class="btn" style="background-color: #79aec8; color: white;" value="Batal" onclick="window.location=document.referrer;">
                            </div>
                            <div class="modal fade" id="myModal" style="display: none;">
                                <div class="modal-dialog">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <h4 class="modal-title" style="margin: 0 auto;">Konfirmasi Ubah Password</h4>
                                        </div>
                                        <div class="modal-body">
                                            <p>Apakah anda yakin ingin mengubah password anda ?</p>
                                        </div>
                                        <div class="modal-footer">
                                            <input type="submit" value="Ubah" class="btn" style="background-color:#417690; color: white;"></input>
                                            <button type="button" class="btn" style="background-color:#79aec8; color: white;" data-dismiss="modal">Tidak</button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                    </div>            
                </div>
            </div>
        </center>
    </section>
    {% endblock %}
    {% block extrajs%}
    <script src="/static/assets/bootstrap/js/bootstrap-select.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@9"></script>
    <script>
        $('#id_username').attr('readonly',true);
        var id = $('#status').val();
        if (id == 1){
            document.getElementById("isi").style.display = "none";
        }
        </script>
        {% endblock %}

sishasembapo/templates/changeprofile.html
{% extends  "layout/pengunjung/base_pengunjung.html" %}

{% load static %}

{% block extrastyle %}
<link rel="stylesheet" href="/static/assets/bootstrap/css/bootstrap-select.css">
<style>

    @media screen and (max-width: 450px) {
        h3 {
            font-size: x-large;
        }
        label {
            font-size: medium;
        }
        .col-sm-10{
            font-size: medium;
        }
    }
</style>
{% endblock%}

{% block content %}

<section class="content-header">
    <!-- Horizontal Form -->
    <center>
        <div class="card col-md-5" style="text-align: left;">
            <div class="card-body">
                <div class="box box-primary col-md-12">
                    <div class="box-header with-border">
                        <h3 class="box-title"><i class="fa fa-user"></i> Profil <b> - {{ request.session.nama }}</b></h3>
                    </div>
                    <!-- /.box-header -->
                    <!-- form start -->
                    <div class="col-md-12 col-xs-12 col-lg-12">     
                        <br>   
                        <form class="form-horizontal" method="POST">
                            {% csrf_token %}
                            <div class="box-body">
                                <div class="form-group">
                                    <label for="nama" class="col-sm-6 control-label">Nama: </label>
                                    <div class="col-sm-10">
                                        {{user.nama}}
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label for="first_name" class="col-sm-6 control-label">Jenis Kelamin: </label>
                                    <div class="col-sm-10">
                                        {{user.get_jenis_kelamin_display}}
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label for="first_name" class="col-sm-6 control-label">Tempat Tanggal lahir: </label>
                                    <div class="col-sm-10">
                                        {{user.tempat_lahir}}, {{user.Tanggal_lahir|date:"j F Y"}} 
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label for="first_name" class="col-sm-6 control-label">Alamat: </label>
                                    <div class="col-sm-10">
                                        {{user.alamat}}
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label for="first_name" class="col-sm-6 control-label">Pasar: </label>
                                    <div class="col-sm-10">
                                        {{user.pasar.nama_pasar}}
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label for="first_name" class="col-sm-6 control-label">Nomor Telepon: </label>
                                    <div class="col-sm-10">
                                        {{user.No_hp}}
                                    </div>
                                </div>
                                <!-- <div class="col-md-offset-3 col-xs-offset-3 col-lg-offset-3"> -->
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </center>
    </section>
    {% endblock %}
    {% block extrajs%}
    <script src="/static/assets/bootstrap/js/bootstrap-select.js"></script>
    <script>
        $('input').attr('readonly',true);
        $('textarea').attr('readonly',true);
    </script>
    {% endblock %}

sishasembapo/templates/login.html
{% extends "layout/base.html" %}

{% load static %}

{% block extracss %}
<style>
        ::-webkit-input-placeholder {
            text-align: center;
         }
         
         :-moz-placeholder { /* Firefox 18- */
            text-align: center;  
         }
         
         ::-moz-placeholder {  /* Firefox 19+ */
            text-align: center;  
         }
         
         :-ms-input-placeholder {  
            text-align: center; 
         }
</style>
{% endblock %}

{% block content %}
    <section class="login-form">
        <form method="POST" action="{% url 'login' %}" role="login">
            {% csrf_token %}
            {% if messages %}
            <div class="alert alert-danger">
                {% for message in messages %}
                <p>{{ message }}</p>
                {% endfor %}
            </div>
            {% endif %}
            <a href="/">
            <img src="{% static "Images/download.png" %}" style="width: 100%;height: 100%;" class="img-responsive" />
            </a>
            <strong><h5><center>SISHASEMBAPO</center></h5></strong>
            <h6 style="font-size: 15px;"><center>Sistem Informasi Harga Sembilan Bahan Pokok</center></h6>
            <input type="text" name="login_username" placeholder="Nama Pengguna" required class="form-control input-lg" />
            <input type="password" name="login_password" placeholder="Kata Sandi" required class="form-control input-lg" />
            {% if request.GET.next %}
            <input type="hidden" name="next" value="{{request.GET.next}}">
            {% endif %}
            <input class="btn btn-lg btn-block" type="submit" value="Masuk" style="background-color:#417690; color: white;" />
            <p style="text-align: center;">Admin PD.Pasar? <a href="/admin" style="text-align: center;">Klik di sini</a></p>
        </form>
    </section>
{% endblock %}